SOTD: In the Waiting Line - Zero 7

Aim : Where do compsci priests live? - In directory!

- ctime( <TIME> )
  - TIME is type time_t *
  - returns the time as a string
- time( <TIME> )
  - TIME is type time_t *
  - sets the parameter to the current time
-----
- A directory is just a file with specific properties
  - properties such as being executable (programs have this property)
- Moving files is just deleting a line from a directory and adding one to another
  - the directory is not the physical location of the file
-----
* Directories
- A *nix directory is a file containing the names of the files within the directory along with basic information like file type.
- Moving files into/out of a directory means changing the directory file, not actually moving any data.
-----
- You can't actually read directories in a program
  - This could prevent corruption
-----
** opendir - <dirent.h>
- Open a directory file
- This will not change the cwd, it only allows your program to read the contents of the directory file
- opendir( <PATH> );
- Returns a pointer to a directory stream (DIR *)
** closedir - <dirent.h>
- Closes the directory stream and frees the pointer associated with it.
- closedir( <DIRECTORY STREAM> )
** readdir - <dirent.h>
- readdir( <DIRECTORY STREAM> )
- Returns a pointer to the next entry in a directory stream, or NULL if all entries have already been returned.
- struct dirent - <sys/types.h>
  - Directory struct that contains the information sotred in a directory file.
  - Some of the data members
    - d_name: Name of a file
    - d_type: File type as an int
  - example:
    - DIR * d;
    - d = opendir( "somedir" );
    - struct dirent *entry;
    - entry = readdir( d );
** rewinddir - <dirent.h>
- Resets the directory stream to the beginning
- rewinddir( <DIRECTORY STREAM> )
